name: Scorecard Evaluation Workflow
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: Project ID
        required: true
      testset_id:
        description: Testset ID
        required: true
      metric_ids:
        description: Metric IDs
        required: true
  repository_dispatch:
    types: start-evaluation
permissions:
  contents: read
jobs:
  evaluation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        env:
          SCORECARD_API_KEY: ${{ secrets.SCORECARD_API_KEY }}
          PROJECT_ID: ${{ github.event.inputs.project_id ||
            github.event.client_payload.project_id || env.DEFAULT_PROJECT_ID }}
          TESTSET_ID: ${{ github.event.inputs.testset_id ||
            github.event.client_payload.testset_id || env.DEFAULT_TESTSET_ID }}
          METRIC_IDS: ${{ github.event.inputs.metric_ids ||
            github.event.client_payload.metric_ids || env.DEFAULT_METRIC_IDS }}
        run: python3 run_tests.py
